spring:
  application:
    name: config-client
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
eureka:
  client:
    port: 8771
    prefer-same-zone-eureka: true
    service-url:
      default-zone:
        - ${EUREKA_URI:http://localhost:8888/eureka}
    enabled: true


