spring:
  application:
    name: eureka-server
server:
  port: 8761

eureka:
  server:
    renewal-percent-threshold: 0.85 #5 если возникнут проблемы в сети или наш сервер выйдет из строя, мы хотим запретить клиент;
  client:
    register-with-eureka: false
    fetch-registry: false #1 не хотим получать информацию реестра от Eureka Server
    eureka-server-connect-timeout-seconds: 60 #2 время ожидания (одна минута) до истечения тайм-аута соединения с Eureka Server;
    eureka-service-url-poll-interval-seconds: 15 #3 каждые 15 секунд запрашивать изменения об информации с сервера;
    use-dns-for-fetching-service-urls: false #4 запрети dns и укажи явный маршрут к серверам eureka (serviceUrl);
    prefer-same-zone-eureka: true #6(сервер) использовать сервер eureka в той же зоне;
    healthcheck:
      enabled: true
    service-url:
      default-zone:
      - http://localhost:8761/eureka
    log-delta-diff: false

  instance:
      lease-renewal-interval-in-seconds: 20 #8 установить время, по которому сервер будет ожидать эхо-запрос от клиента о том что он жив (20 секунд)
      lease-expiration-duration-in-seconds: 70 #9 Если Eureka Server не видел обновления в течение 70 секунд, он удаляет экземпляр из своего реестра

